#!/bin/bash
set -euo pipefail

#-- "everything here?" checks --#
shared_vars=commands/shared_vars  # todo: will need to be /var/podc/commands/shared_vars
if [ ! -f "$shared_vars" ]; then
    echo "A required file is missing: $shared_vars"
    exit 1
fi
source "$shared_vars"

check_deps_installed
#----#

command="$1"
shift # remove first arg from $@

# todo: check if command is a file in MAIN_COMMAND_DIR, then check if its in the LOCAL_COMMAND_DIR
"$MAIN_COMMAND_DIR/$command" "$@"
