#!/bin/bash
set -euo pipefail

#-- "everything here?" checks --#
shared_vars=commands/shared_vars  # todo: will need to be /var/podc/commands/shared_vars
if [ ! -f "$shared_vars" ]; then
    echo "A required file is missing: $shared_vars"
    exit 1
fi
source "$shared_vars"

check_deps_installed

if [ -z "${1:-}" ] || [ -z "${2:-}" ]; then
    echo "$__usage"
    exit 1
fi
#----#

image_tag="$1"
arg_file="$2"

podman build -f "$DOCKERFILE" --build-arg-file "$arg_file" --tag "$image_tag"
